version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./annuaireuppa.sql:/docker-entrypoint-initdb.d/annuaireuppa.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: annuaireuppa
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "3000:80"
    depends_on:
      - db

volumes:
  db_data:
